models/Book.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "books".
 *
 * @property integer $id
 * @property string $name
 * @property string $date_create
 * @property string $date_update
 * @property string $image
 * @property string $date
 * @property integer $author_id
 *
 * @property Author $author
 */
class Book extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'books';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'date', 'author_id'], 'required'],
            [['date_create', 'date_update', 'date'], 'safe'],
            [['author_id'], 'integer'],
            [['name'], 'string', 'max' => 255],
/*            [['image'], 'file',
                'skipOnEmpty' => false,
                'extensions' => 'png, jpg',
                'checkExtensionByMimeType' => false,
            ],*/
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Наименование',
            'date_create' => 'Дата добавления',
            'date_update' => 'Дата обновления записи',
            'image' => 'Изображение',
            'date' => 'Дата выхода книги',
            'author_id' => 'Автор',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(Author::className(), ['id' => 'author_id']);
    }
}

controllers/BookController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use Imagine\Gd\Imagine;
use Imagine\Image\Box;
use Imagine\Image\ImageInterface;
use app\models\Author;
use app\models\BookSearch;
use app\models\Book;
use app\models\UploadForm;

/**
 * BookController implements the CRUD actions for Book model.
 */
class BookController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Book models.
     * @return mixed
     */
    public function actionIndex()
    {
        // save filter, sort order, page number in session
        Url::remember();

        $searchModel = new BookSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            'authors' => ArrayHelper::map(Author::find()->all(), 'id', function(Author $author) {
                return $author->firstname . ' ' . $author->lastname;
            })
        ]);
    }

    /**
     * Show thumbnail of book image
     *
     * @param int $id
     * @throws NotFoundHttpException
     */
    public function actionThumb($id)
    {
        $model   = $this->findModel($id);
        $imagine = new Imagine();
        $size    = new Box(40, 40);
        $mode    = ImageInterface::THUMBNAIL_INSET;
        $imagine->open(UploadForm::UPLOAD_PATH . $model->image)->thumbnail($size, $mode)->show('jpg');
    }

    /**
     * Show book image
     *
     * @param int $id
     * @throws NotFoundHttpException
     */
    public function actionImage($id)
    {
        $model   = $this->findModel($id);
        $imagine = new Imagine();
        $size    = new Box(850, 850);
        $mode    = ImageInterface::THUMBNAIL_INSET;
        $imagine->open(UploadForm::UPLOAD_PATH . $model->image)->thumbnail($size, $mode)->show('jpg');
    }

    /**
     * Displays a single Book model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $book = $this->findModel($id);
        return $this->renderAjax('view', [
            'book' => $book,
            'author' => Author::findOne($book->author_id)
        ]);
    }

    /**
     * Creates a new Book model.
     * If creation is successful, the browser will be redirected to the 'index' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Book();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(Url::previous());
        }
        return $this->render('create', [
            'model' => $model,
            'authors' => ArrayHelper::map(Author::find()->all(), 'id', function(Author $author) {
                return $author->firstname . ' ' . $author->lastname;
            })
        ]);
    }

    /**
     * Updates an existing Book model.
     * If update is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(Url::previous());
        } else {
            return $this->render('update', [
                'model' => $model,
                'authors' => ArrayHelper::map(Author::find()->all(), 'id', function(Author $author) {
                    return $author->firstname . ' ' . $author->lastname;
                }),
            ]);
        }
    }

    /**
     * Deletes an existing Book model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->delete();
        @unlink(UploadForm::UPLOAD_PATH . $model->image);
        return $this->redirect(['index']);
    }

    /**
     * Render form for image uploading and upload image.
     *
     * @param string $id
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionUpload($id)
    {
        $model = new UploadForm();

        if (Yii::$app->request->isPost) {
            $book = $this->findModel(Yii::$app->request->post('id'));
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            if ($filename = $model->upload()) {
                // remove old image
                if ( ! empty($book->image)) {
                    @unlink(UploadForm::UPLOAD_PATH . $book->image);
                }
                // save image filename
                $book->image = $filename;
                if ($book->save()) {
                    return $this->redirect(Url::previous());
                }
            }
        }

        return $this->render('upload_image', [
            'book' => $this->findModel($id),
            'model' => $model,
        ]);
    }

    /**
     * Finds the Book model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Book the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Book::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/book/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View            $this
 * @var app\models\Book         $model
 * @var array                   $authors
 * @var yii\widgets\ActiveForm  $form
 */
?>

<div class="book-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'date')->textInput(['type' => 'date']) ?>

    <?= $form->field($model, 'author_id')->dropDownList($authors, ['prompt'=>'Select...']) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Обновить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/book/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View            $this
 * @var yii\widgets\ActiveForm  $form
 * @var app\models\BookSearch   $model
 * @var array                   $authors
 */
?>

<div class="book-search">

    <?php $form = ActiveForm::begin([
        'id' => 'filter-form',
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <div class="panel panel-info">
        <div class="panel-heading">
            Фильтр
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-4">
                    <?= $form->field($model, 'name') ?>
                </div>
                <div class="col-md-2">
                    <?= $form->field($model, 'date_start')->textInput(['type' => 'date']) ?>
                </div>
                <div class="col-md-2">
                    <?= $form->field($model, 'date_end')->textInput(['type' => 'date']) ?>
                </div>
                <div class="col-md-4">
                    <?= $form->field($model, 'author_id')->dropDownList($authors, ['prompt'=>'Select...']) ?>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <?= Html::submitButton('Фильтр', ['class' => 'btn btn-primary']) ?>
            <?= Html::button('Сброс', ['class' => 'btn btn-default reset']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/book/create.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View        $this
 * @var app\models\Book     $model
 * @var array               $authors
 */

$this->title = 'Новая запись';
$this->params['breadcrumbs'][] = ['label' => 'Книги', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="book-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model'   => $model,
        'authors' => $authors,
    ]) ?>

</div>

views/book/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\bootstrap\Modal;
use yii\web\JqueryAsset;

/**
 * @var yii\web\View                $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\BookSearch       $searchModel
 * @var array                       $authors
 */

$this->title = 'Книги';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="book-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php echo $this->render('_search', [
        'model' => $searchModel,
        'authors' => $authors
    ]); ?>

    <p>
        <?= Html::a('Создать запись', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            [
                'label'  => 'Превью',
                'format' => 'raw',
                'value'  => function($data) {
                    if ( ! empty($data['image'])) {
                        $val = Html::a(
                            Html::img(Url::toRoute(['book/thumb', 'id' => $data['id']])), '#', [
                                'class' => 'preview',
                                'data-image-url' => Url::toRoute(['book/image', 'id' => $data['id']])
                            ]
                        );
                    } else {
                        $val = 'No photo';
                    }
                    $val .= '&nbsp;'
                        . Html::a('<span class="glyphicon glyphicon-upload"></span>',
                            Url::toRoute(['book/upload', 'id' => $data['id']]),
                            [
                                'class' => 'upload-image',
                                'title' => 'Загрузка изображения'
                            ]
                        );
                    return $val;
                }
            ],
            [
                'attribute' => 'full_name',
                'label' => 'Автор',
                'content' => function($data) {
                    /** @var \app\models\Author $author */
                    $author = $data['author'];
                    return $author->getFullName();
                }
            ],
            [
                'attribute' => 'date',
                'format'    => ['date', 'php:d.m.Y'],
            ],
            [
                'attribute' => 'date_create',
                'format'    => ['date', 'php:d.m.Y h:i:s'],
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'buttons' => [
                    'view' => function ($url) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>','#', [
                            'class' => 'book-view',
                            'title' => 'Просмотр',
                            'data-view-url' => $url
                        ]);
                    },
                ],
            ],
        ],
    ]); ?>

    <?php
    Modal::begin([
        'id' => 'bookViewModal',
        'header' => '<h3>Инфо</h3>',
        'size' => 'modal-lg',
    ]);
    echo '<div id="bookInfo"></div>';
    Modal::end();
    ?>

    <?php
    Modal::begin([
        'id' => 'bookImageModal',
        'header' => '<h3>Изображение</h3>',
        'size' => 'modal-lg',
    ]);
    echo '<div id="bookImage" style="text-align: center"></div>';
    Modal::end();
    ?>

</div>
<?php
$this->registerJsFile(Yii::getAlias('@web/js/book.js'), ['depends' => JqueryAsset::className()]);
?>

views/book/update.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View        $this
 * @var app\models\Book     $model
 * @var array               $authors
 */

$this->title = 'Обновить книгу: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Книги', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="book-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'authors' => $authors,
    ]) ?>

</div>

views/book/upload_image.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View            $this
 * @var app\models\Book         $book
 * @var app\models\UploadForm   $model
 */

$this->title = 'Загрузить картинку для : ' . ' ' . $book->name;
$this->params['breadcrumbs'][] = ['label' => 'Books', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Upload';
?>
<div class="book-update">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="book-form">
        <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>

            <input type="hidden" name="id" value="<?= $book->id ?>">
            <?= $form->field($model, 'imageFile')->fileInput() ?>

            <div class="form-group">
                <?= Html::submitButton('Загрузить', ['class' => 'btn btn-primary']) ?>
            </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

views/book/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;

/**
 * @var yii\web\View        $this
 * @var app\models\Book     $book
 * @var app\models\Author   $author
 */

$this->params['breadcrumbs'][] = ['label' => 'Books', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="book-view">
    <?= DetailView::widget([
        'model' => $book,
        'attributes' => [
            'id',
            'name',
            [
                'label'  => 'Превью',
                'format' => 'raw',
                'value'  => ( ! empty($book->image))
                    ? Html::a(Html::img(Url::toRoute(['book/thumb', 'id' => $book->id])), '#', [
                        'id' => 'bookThumb',
                        'class' => 'preview',
                        'data-image-url' => Url::toRoute(['book/image', 'id' => $book->id])
                    ])
                    : 'No photo',
            ],
            [
                'attribute' => 'date',
                'format'    => ['date', 'php:d.m.Y'],
            ],
            [
                'attribute' => 'date_create',
                'format'    => ['date', 'php:d.m.Y h:i:s'],
            ],
            [
                'attribute' => 'date_update',
                'format'    => ['date', 'php:d.m.Y h:i:s'],
            ],
            [
                'attribute' => 'author_id',
                'label' => 'Автор',
                'value' => $author->getFullName()
            ],
        ],
    ]) ?>

</div>